### PR TITLE
Ignore stderr message if no native zip

### PR DESCRIPTION
**Pull request by BenRussert**
This will prevent stderr from showing confusing zip not recognized message:
"no zip found message"

on windows when bestzip is still working, but will use node zip instead.

### CODE REVIEW

**Comment by nfriedly** [comment]
Hey @BenRussert thanks, this is a good idea!

The linter is complaining about formatting, you can run `npm run lint-fix` and it'll straighten it out automatically. After that, I think we can merge this in and release it.

**Comment by BenRussert** [comment]
> Hey @BenRussert thanks, this is a good idea!
> 
> The linter is complaining about formatting, you can run `npm run lint-fix` and it'll straighten it out automatically. After that, I think we can merge this in and release it.

Thanks for the quick reply, glad you are happy with the change and thanks for the nice useful (and cross platform) utility!

**Comment by nfriedly** [comment]
Awesome! I'm on my phone right now, so I can merge, but not release. I'll get the release out soon.

**Comment by BenRussert** [comment]
🚢 🚢 :shipit:

**Comment by nfriedly** [comment]
So sorry! I forgot about this. It should be released in v2.1.5 by Travis CI shortly.

**Pull request merged**
